// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWoQTzsYwb-isweq7qeVDoFMnbSF5360I',
    appId: '1:69634161986:web:09456690ee95eb4f181cdb',
    messagingSenderId: '69634161986',
    projectId: 'resturantreservationapp',
    authDomain: 'resturantreservationapp.firebaseapp.com',
    storageBucket: 'resturantreservationapp.appspot.com',
    measurementId: 'G-6YRRPP3ZR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi086rZjwqM-CzlLHwFB9P3GemZSMfGfk',
    appId: '1:69634161986:android:188dbdd64d5bef1f181cdb',
    messagingSenderId: '69634161986',
    projectId: 'resturantreservationapp',
    storageBucket: 'resturantreservationapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFC7G9wKjyp6__kTVRFNcQDKDjsF8mdd8',
    appId: '1:69634161986:ios:e0d431bd99f72496181cdb',
    messagingSenderId: '69634161986',
    projectId: 'resturantreservationapp',
    storageBucket: 'resturantreservationapp.appspot.com',
    iosBundleId: 'com.example.flutterApplication16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFC7G9wKjyp6__kTVRFNcQDKDjsF8mdd8',
    appId: '1:69634161986:ios:e0d431bd99f72496181cdb',
    messagingSenderId: '69634161986',
    projectId: 'resturantreservationapp',
    storageBucket: 'resturantreservationapp.appspot.com',
    iosBundleId: 'com.example.flutterApplication16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWoQTzsYwb-isweq7qeVDoFMnbSF5360I',
    appId: '1:69634161986:web:09456690ee95eb4f181cdb',
    messagingSenderId: '69634161986',
    projectId: 'resturantreservationapp',
    authDomain: 'resturantreservationapp.firebaseapp.com',
    storageBucket: 'resturantreservationapp.appspot.com',
    measurementId: 'G-6YRRPP3ZR5',
  );

}